let content = { courses: [], testimonials: [], faqs: [], offerLetters: [], studyMaterials: [], demoClass: {} };
const byId = (id) => document.querySelector(`#${id}`);
const escape = (value = '') => String(value).replace(/[&<>"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[character]);
const field = (label, key, value, wide = false) => `<label class="${wide ? 'wide' : ''}">${label}<input data-key="${key}" value="${escape(value)}"></label>`;
const textareaField = (label, key, value, wide = true) => `<label class="${wide ? 'wide' : ''}">${label}<textarea data-key="${key}">${escape(value)}</textarea></label>`;

const render = () => {
  byId('courses').innerHTML = content.courses.map((course, index) => `<article data-index="${index}" data-type="courses"><div class="grid">${field('Course title', 'title', course.title, true)}${field('Duration', 'duration', course.duration)}${field('Current price', 'price', course.price)}${field('Previous price', 'oldPrice', course.oldPrice)}${field('Price note', 'note', course.note)}<label>Featured course<input data-key="featured" type="checkbox" ${course.featured ? 'checked' : ''}></label><label>Show on website<input data-key="visible" type="checkbox" ${course.visible !== false ? 'checked' : ''}></label></div><button class="remove" type="button">Remove course</button></article>`).join('');
  byId('testimonials').innerHTML = content.testimonials.map((item, index) => `<article data-index="${index}" data-type="testimonials"><div class="grid">${textareaField('Testimonial', 'quote', item.quote)}${field('Name', 'name', item.name)}${field('Role', 'role', item.role)}<label>Show on website<input data-key="visible" type="checkbox" ${item.visible !== false ? 'checked' : ''}></label><label class="wide">Proof image / offer letter (PNG, JPG or WebP, max 5 MB)<input data-key="proofUpload" type="file" accept="image/png,image/jpeg,image/webp">${item.proofImage ? `<a class="proof-link" href="/${escape(item.proofImage)}" target="_blank" rel="noopener">View uploaded proof</a>` : ''}</label></div><button class="remove" type="button">Remove testimonial</button></article>`).join('');
  byId('faqs').innerHTML = content.faqs.map((item, index) => `<article data-index="${index}" data-type="faqs"><div class="grid">${field('Question', 'question', item.question, true)}${textareaField('Answer', 'answer', item.answer)}<label>Show on website<input data-key="visible" type="checkbox" ${item.visible !== false ? 'checked' : ''}></label></div><button class="remove" type="button">Remove FAQ</button></article>`).join('');
  byId('study-materials').innerHTML = content.studyMaterials.map((item, index) => `<article data-index="${index}" data-type="studyMaterials"><div class="grid">${field('Study material title', 'title', item.title, true)}${field('Institute / brand', 'institution', item.institution)}${field('Edition', 'edition', item.edition)}${field('Qualification / subtitle', 'subtitle', item.subtitle, true)}${textareaField('Description', 'description', item.description)}${field('Original price', 'oldPrice', item.oldPrice)}${field('Offer price', 'price', item.price)}${field('Price note', 'note', item.note)}${textareaField('WhatsApp request message', 'whatsappMessage', item.whatsappMessage)}<label>Show on website<input data-key="visible" type="checkbox" ${item.visible !== false ? 'checked' : ''}></label></div><button class="remove" type="button">Remove study material</button></article>`).join('');
  const demo = content.demoClass || {};
  byId('demo-class').innerHTML = `<article data-type="demoClass"><div class="grid">${field('Demo-class title', 'title', demo.title, true)}${textareaField('Description', 'description', demo.description)}${textareaField('Contact message', 'contactMessage', demo.contactMessage)}${field('WhatsApp or meeting link', 'meetingLink', demo.meetingLink, true)}${field('Button label', 'buttonLabel', demo.buttonLabel)}<label>Show on website<input data-key="visible" type="checkbox" ${demo.visible !== false ? 'checked' : ''}></label></div></article>`;
  byId('offer-letters').innerHTML = content.offerLetters.map((item, index) => `<article data-index="${index}" data-type="offerLetters"><div class="grid"><label>Show on website<input data-key="visible" type="checkbox" ${item.visible !== false ? 'checked' : ''}></label><label class="wide">Offer-letter image (PNG, JPG or WebP, max 5 MB)<input data-key="offerLetterUpload" type="file" accept="image/png,image/jpeg,image/webp">${item.image ? `<a class="proof-link" href="/${escape(item.image)}" target="_blank" rel="noopener">View uploaded offer letter</a>` : ''}</label></div><button class="remove" type="button">Remove offer letter</button></article>`).join('');
};

document.addEventListener('input', (event) => { const article = event.target.closest('article'); if (!article || !event.target.dataset.key || event.target.type === 'file') return; const value = event.target.type === 'checkbox' ? event.target.checked : event.target.value; if (article.dataset.type === 'demoClass') content.demoClass[event.target.dataset.key] = value; else content[article.dataset.type][article.dataset.index][event.target.dataset.key] = value; });
document.addEventListener('change', (event) => {
  const article = event.target.closest('article'); const file = event.target.files?.[0]; const key = event.target.dataset.key;
  if (!article || !file || !['proofUpload', 'offerLetterUpload'].includes(key)) return;
  const allowedType = ['image/png', 'image/jpeg', 'image/webp'].includes(file.type) || /\.(png|jpe?g|webp)$/i.test(file.name);
  if (!allowedType) { byId('status').textContent = 'Unsupported image type. Please upload only PNG, JPG, or WebP images.'; event.target.value = ''; return; }
  if (file.size > 5 * 1024 * 1024) { byId('status').textContent = 'Image is too large. The maximum allowed size is 5 MB.'; event.target.value = ''; return; }
  const reader = new FileReader(); reader.onload = () => { const item = content[article.dataset.type][article.dataset.index]; if (key === 'proofUpload') item.proofImageData = reader.result; else item.imageData = reader.result; byId('status').textContent = 'Image ready to save.'; }; reader.readAsDataURL(file);
});
document.addEventListener('click', (event) => { const article = event.target.closest('article'); if (event.target.classList.contains('remove') && article) { content[article.dataset.type].splice(article.dataset.index, 1); render(); } });
byId('add-course').onclick = () => { content.courses.push({ title: 'New course', duration: '', oldPrice: '', price: '', note: '', featured: false, visible: true }); render(); };
byId('add-testimonial').onclick = () => { content.testimonials.push({ quote: '', name: '', role: '', visible: true }); render(); };
byId('add-faq').onclick = () => { content.faqs.push({ question: 'New question', answer: '', visible: true }); render(); };
byId('add-study-material').onclick = () => { content.studyMaterials.push({ title: 'New study material', institution: 'RV Consulting Institute', edition: '', subtitle: '', description: '', oldPrice: '', price: '', note: 'Study-material access', whatsappMessage: 'Hi RV Consulting, I want to get access to the study material notes.', visible: true }); render(); };
byId('add-offer-letter').onclick = () => { content.offerLetters.push({ visible: true }); render(); };
byId('content-form').onsubmit = async (event) => { event.preventDefault(); const status = byId('status'); status.textContent = 'Saving…'; try { const response = await fetch('/api/content', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(content) }); if (response.ok) { content = await response.json(); content.studyMaterials ||= []; content.offerLetters ||= []; content.demoClass ||= {}; render(); status.textContent = 'Saved. Your website is updated.'; } else { const result = await response.json().catch(() => ({})); status.textContent = result.error || 'Unable to save changes.'; } } catch (_) { status.textContent = 'Unable to save changes. Please check your connection and try again.'; } };
fetch('/api/content').then((response) => response.json()).then((data) => { content = { ...content, ...data, offerLetters: data.offerLetters || [], studyMaterials: data.studyMaterials || [], demoClass: data.demoClass || {} }; render(); }).catch(() => { byId('status').textContent = 'Unable to load content.'; });
